### ISSUE TITLE
extention doesn't work

### ISSUE THREAD

**Issue by kingjolab** [wpp/ScreenStream#3]
Hi, when I try your index.html file, and put the folder to chrome extension. it's still doesn't work. by the way, is it necessary to use ruby as server side ? and ssl ?

**Comment by wpp** [comment]
Hi @kingjolab sorry for not getting back earlier, I somehow didn't get an email for this issue.

Correct me if I'm wrong but you're probably getting the
![alert](https://cloud.githubusercontent.com/assets/942021/13181008/3cfcc026-d72b-11e5-8c03-bd707be3f1d4.png)
 alert after installing the extension.

If that is indeed the case, the extension will not be invoked when opening the file from your filesystem. You could add  `"file://*"` to the manifest.json and remove the origin check `if (event.origin != window.location.origin) return;` from app.js.

However you'd still have a problem with the `getUserMediaCall`.

So yes I'd say a server with SSL is required. Doesn't have to be a ruby server as long as the url matches the one in manifest.json (`https://localhost:8000`) you should be fine.

http://stackoverflow.com/questions/13723699/chrome-getusermedia-not-requesting-permission-locally

**Comment by wpp** [comment]
I'm closing this, since the extension worked for me on Chrome Version 48.0.2564.109 (64-bit). And the requirements are listed in the README.

**Comment by antoinerousseau** [comment]
why https and not http? http is supposed to be enough for localhost, no?

**Comment by wpp** [comment]
I had a look again and you can now run the demo without a server. You can simply serve it from the file system.
