### ISSUE TITLE
desktopcapture can not close?

### ISSUE THREAD

**Issue by zegodev** [wpp/ScreenStream#4]
i try stop capture  by 'chrome.desktopCapture.cancelChooseDesktopMedia(desktopMediaRequestId)';
but seams not working both on mac and window; any solution?

**Comment by wpp** [comment]
Hm are you certain you're supplying the `desktopMediaRequestId`? https://github.com/wpp/ScreenStream/blob/e45026e876974cb79e2a8890e3d9e8d846d5f7fb/extension/background.js#L41

If that's the case you might want to file or comment on [crbug.com](), [there is a similar issue but it has been marked as resolved](https://bugs.chromium.org/p/chromium/issues/detail?id=383999&can=1&q=cancelChooseDesktopMedia&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).
